class ShowoffSlideStream
  def initialize(paths_for_markdown)
    content = ''
    paths_for_markdown.each { |p| content << IO.read(p) }
    @slides = []
    content.split(/!SLIDE/).each do |slide|
      @slides << ShowOffSlide.new(CGI.unescapeHTML(slide))
    end
  end
  
  def to_pdf
    pdf = Prawn::Document.new(:page_size => 'A4', :page_layout => :portrait)
    pdf.text ShowOffUtils.showoff_title, :size => 45, :inline_format => true
    pdf.text "by <b>#{ShowOffUtils.showoff_author}</b>", :size => 30, :inline_format => true
    pdf.move_down(200)
    pdf.text ShowOffUtils.showoff_description, :size => 20
    pdf.bounding_box([0,100], :width => pdf.bounds.width, :height => 150) do
      pdf.horizontal_rule
      pdf.stroke
      pdf.move_down(5)
      pdf.text 'Generated by <b>showoff2pdf</b> by Ryan Stenhouse', :inline_format => true
      pdf.text '<link href="http://github.com/HHRy"><u>http://github.com/HHRy</u></link>    |    <link href="http://ryanstenhouse.eu"><u>http://ryanstenhouse.eu</u></link>', :inline_format => true
   end
    @slides.each { |slide| slide.render_on(pdf)  }
    pdf
  end
end
